
openapi: 3.0.0
info:
  title: a
  description: A sample.
  version: "1.0"
servers:
  - url: http://localhost/cloudmesh/a
    description: Optional server description, e.g. Main (production) server
paths:
  /a:
     get:
      summary: A sample.
      description: Optional extended description in CommonMark or HTML.
      operationId: a
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            text/plain:
              schema: 
                type: integer
      parameters:
         
         - in: query
           name: x
           schema:
             type: integer
           description: not yet available, you can read it from docstring

         - in: query
           name: y
           schema:
             type: number
           description: not yet available, you can read it from docstring
 
      
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
